name: CI Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  native-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.0'
          java-version: '21'
          distribution: 'graalvm'
          cache: 'maven'

      - name: Build Native Executable
        run: >
          ./mvnw -B --file pom.xml verify -Pnative
          -Dquarkus.native.additional-build-args=-H:-UseContainerSupport